In [16]:
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
import numpy as np
from gsmmutils.model import MyModel

In [212]:
model_c5 = MyModel(r"/home/ecunha/omics-integration/results/ngaditana/PRJNA589063/integration/models/C5_gimme_0.4_loopless.xml", "e_Biomass__cytop")
model_n5 = MyModel(r"/home/ecunha/omics-integration/results/ngaditana/PRJNA589063/integration/models/N5_gimme_0.4_loopless.xml", "e_Biomass__cytop")
for met in model_c5.metabolites:
    met.id = met.id.split("[")[0]
for met in model_n5.metabolites:
    met.id = met.id.split("[")[0]

Loading

Reactions: 2144
Metabolites: 1805
Genes: 808
Model loaded
Loading

Reactions: 2307
Metabolites: 1895
Genes: 840
Model loaded

In [131]:
c5 = pd.read_csv("/home/ecunha/omics-integration/results/ngaditana/PRJNA589063/dfa/C5_gimme_0.4_loopless_ACHR_ACHR_samples_no_reverse.csv", sep="\t")
c5.head()

,T_O2tm__mitmem,BMGR6355__er,BMGR6010__nucl,R01652__cytop,R00243__mito,DGTSS_205_205__er,BMGR3616__er,PKS_C204__cytop,TO0000017tm__mitmem,BMGR0422__chlo,...,BMGR6128__ermem,BMGR4765__ermem,MGDGS_205_205__chlo,RXN_12968__er,T_ORNth__chlomem,R03066__cytop,BMGR6404__lip,T_HMGCOAtm__mitmem,PPACO__chlo,EX_C00009__dra
0,7.403838,0.000018,0.000490,0.005504,-15.057075,0.000189,0.000286,0.000107,0.000015,0.000124,...,-0.000022,-0.001088,0.000452,0.000951,-0.004085,0.000034,0.000005,0.462649,0.000041,-18.688203
1,7.397820,0.000018,0.000489,0.005503,-15.051350,0.000189,0.000403,0.000107,0.000015,0.000126,...,-0.000022,-0.001087,0.000452,0.000951,-0.004087,0.000034,0.000122,0.462893,0.000041,-18.637541
2,7.383461,0.000018,0.000484,0.005505,-15.071244,0.000189,0.000462,0.000112,0.000015,0.000127,...,-0.000022,-0.001089,0.000453,0.000948,-0.004096,0.000034,0.000180,0.460996,0.000041,-18.596657
3,7.116492,0.000018,0.000486,0.005352,-16.200775,0.000189,0.000442,0.000101,0.000015,0.000097,...,-0.000022,-0.001504,0.000452,0.000955,-0.004082,0.000034,0.000160,0.509263,0.000041,-18.019943
4,7.136467,0.000018,0.000113,0.005338,-16.175622,0.000189,0.000607,0.000099,0.000015,0.000097,...,-0.000022,-0.001502,0.000453,0.000958,-0.004094,0.000034,0.000324,0.507414,0.000041,-18.046339

In [132]:
n5 = pd.read_csv("/home/ecunha/omics-integration/results/ngaditana/PRJNA589063/dfa/N5_gimme_0.4_loopless_ACHR_ACHR_samples_no_reverse.csv", sep="\t")
n5.head()

,T_O2tm__mitmem,BMGR6355__er,R01652__cytop,R00243__mito,DGTSS_205_205__er,BMGR3616__er,PKS_C204__cytop,TO0000017tm__mitmem,BMGR0422__chlo,R04537__cytop,...,BMGR6128__ermem,BMGR4765__ermem,MGDGS_205_205__chlo,RXN_12968__er,T_ORNth__chlomem,R03066__cytop,BMGR6404__lip,T_HMGCOAtm__mitmem,PPACO__chlo,EX_C00009__dra
0,16.034077,0.000005,0.005418,-6.510764,0.000186,0.000349,0.000116,0.000058,0.000070,0.018001,...,-0.000038,-3.010251,0.000445,0.000781,-0.004018,0.000034,0.000005,0.000000,0.00004,-10.375796
1,16.034062,0.000005,0.005419,-6.510962,0.000186,0.000349,0.000116,0.000058,0.000070,0.018001,...,-0.000038,-3.010251,0.000445,0.000782,-0.004018,0.000034,0.000005,0.000000,0.00004,-10.373638
2,15.971644,0.000005,0.005370,-6.469193,0.000185,0.000875,0.000124,0.000059,0.000070,0.018179,...,-0.000037,-3.009865,0.000442,0.000765,-0.003997,0.000034,0.000533,0.000002,0.00004,-10.299087
3,15.971912,0.000005,0.005371,-6.467159,0.000185,0.000747,0.000124,0.000059,0.000070,0.018168,...,-0.000037,-3.009580,0.000443,0.000766,-0.003998,0.000034,0.000404,0.000002,0.00004,-10.297735
4,15.976710,0.000005,0.005367,-6.638774,0.000185,0.000696,0.000124,0.000059,0.000074,0.018181,...,-0.000037,-3.008836,0.000442,0.000765,-0.003996,0.000034,0.000354,0.000002,0.00004,-10.219977

In [126]:
df = pd.read_csv("/home/ecunha/omics-integration/results/ngaditana/PRJNA589063/dfa/C5_gimme_0.4_loopless_ACHR_N5_gimme_0.4_loopless_ACHR_results.csv")

In [176]:
df.loc[df.Reaction.str.contains("R00351")]

,Reaction,Pvalue,Padj,Reject,FC,Padj_bootstrap
465,R00351__mito,2.979878e-200,1.312471e-199,True,0.539285,NaN
667,R00351__pero,0.000000e+00,0.000000e+00,True,-1.000000,NaN

In [218]:
for r in model_c5.metabolites.get_by_id("C00011__extr").reactions:
    print(f"{r.id, c5[r.id].mean()}")

('EX_C00011__dra', -1.3403986287000003)
('T_CO2__plas', 1.3403986287000003)

In [217]:
for r in model_n5.metabolites.get_by_id("C00011__extr").reactions:
    print(f"{r.id, n5[r.id].mean()}")

('T_CO2__plas', 1.4512464469000002)
('EX_C00011__dra', -1.4512464469000002)

In [231]:
df.head()

,Reaction,Pvalue,Padj,Reject,FC,Padj_bootstrap
0,T_FADtx__permem,1.245206e-308,6.185462e-308,True,-0.636783,NaN
1,DGDGS_205_205__chlo,4.231712e-40,1.056329e-39,True,0.457317,NaN
2,BMGR4874__chlomem,0.000000e+00,0.000000e+00,True,-1.000000,NaN
3,R10179__mito,4.153111e-77,1.298339e-76,True,-0.345106,NaN
4,T_PC161161tr__ermem,3.958740e-05,4.569728e-05,True,-0.435636,NaN

In [236]:
more_100 = [col for col in c5.columns if c5[col].abs().max()>100]

In [237]:
more_100

['T_MALOAAtx__permem',
 'R10092__cytop',
 'R00342__pero',
 'R01361__pero',
 'T_PPAth__chlomem',
 'T_COAth__chlomem',
 'T_PPCOAth__chlomem',
 'R00926__cytop',
 'R00355__mito',
 'T_Htx__permem',
 'TR2300023tm__mitmem',
 'PRISM_white_LED__extr',
 'DM_photon490__chlo',
 'R01354__chlo',
 'R00206__chlo',
 'R01354__cytop',
 'T_CO2th__chlomem',
 'R00926__chlo',
 'DM_photon646__chlo',
 'TR2000129tm__mitmem',
 'T_AKGCITtm__mitmem',
 'R00355__cytop',
 'T_BHBtx__permem',
 'TR2000137tm__mitmem',
 'T_ACACtx__permem',
 'EX_C00205__dra']

In [222]:
print(f"C5: {c5['R09503_hn673__lum'].mean()}")

C5: 17.452689995300002

In [223]:
print(f"N5: {n5['R09503_hn673__lum'].mean()}")

N5: 17.4617857031